name = "ai-contract-generator-frontend"
main = "dist/index.html"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"

[env.production]
name = "ai-contract-generator-frontend-prod"

[env.staging]
name = "ai-contract-generator-frontend-staging"
